In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

In [2]:
data = pd.read_csv("C:\ANU\Smart Sys\Assignment_2\Gaming and Mental Health.csv")

In [3]:
data.head(5)

,record_id,age,gender,daily_gaming_hours,game_genre,primary_game,gaming_platform,sleep_hours,sleep_quality,sleep_disruption_frequency,...,continued_despite_problems,eye_strain,back_neck_pain,weight_change_kg,exercise_hours_weekly,social_isolation_score,face_to_face_social_hours_weekly,monthly_game_spending_usd,years_gaming,gaming_addiction_risk_level
0,GD0001,17,Male,11.1,Mobile Games,Clash of Clans,PC,3.7,Very Poor,Sometimes,...,True,True,False,6.8,3.7,7,1.3,383.70,3,Severe
1,GD0002,21,Male,3.0,MOBA,Dota 2,PC,7.2,Fair,Rarely,...,False,False,False,0.4,8.5,2,10.7,46.64,1,Low
2,GD0003,23,Male,7.6,FPS,CS:GO,Multi-platform,4.4,Fair,Often,...,True,False,True,1.8,7.1,5,3.2,100.81,6,Severe
3,GD0004,20,Female,7.2,RPG,Skyrim,Multi-platform,5.1,Fair,Often,...,False,True,True,0.2,5.2,4,9.1,51.60,7,High
4,GD0005,18,Male,6.8,Battle Royale,Apex Legends,PC,3.4,Poor,Never,...,False,False,False,0.5,6.1,4,4.5,32.57,1,Moderate

In [4]:
valorant_data = data[data['primary_game'] == 'Valorant']
valorant_data

,record_id,age,gender,daily_gaming_hours,game_genre,primary_game,gaming_platform,sleep_hours,sleep_quality,sleep_disruption_frequency,...,continued_despite_problems,eye_strain,back_neck_pain,weight_change_kg,exercise_hours_weekly,social_isolation_score,face_to_face_social_hours_weekly,monthly_game_spending_usd,years_gaming,gaming_addiction_risk_level
41,GD0042,16,Male,8.0,FPS,Valorant,Mobile,3.8,Poor,Sometimes,...,True,True,True,0.9,6.0,8,6.3,61.37,1,Severe
63,GD0064,19,Female,6.6,FPS,Valorant,Mobile,3.3,Very Poor,Often,...,False,True,True,2.3,8.0,4,9.5,144.41,9,High
100,GD0101,21,Male,5.4,FPS,Valorant,PC,6.6,Fair,Rarely,...,False,True,False,1.3,5.7,1,11.2,33.12,11,Low
106,GD0107,14,Female,2.9,FPS,Valorant,Mobile,7.9,Good,Never,...,False,False,False,0.5,9.4,3,8.7,24.60,3,Low
174,GD0175,25,Male,7.9,FPS,Valorant,Multi-platform,5.1,Fair,Sometimes,...,False,True,False,0.5,7.4,5,3.3,53.96,7,Moderate
190,GD0191,18,Male,4.2,FPS,Valorant,Mobile,6.1,Poor,Never,...,False,False,False,0.6,7.2,1,9.5,6.99,7,Low
241,GD0242,24,Male,0.7,FPS,Valorant,Multi-platform,8.3,Good,Often,...,False,False,False,0.3,9.5,1,11.0,6.93,7,Low
269,GD0270,20,Female,2.8,FPS,Valorant,Console,8.0,Good,Never,...,False,False,False,1.3,6.5,3,10.0,13.40,9,Low
289,GD0290,21,Female,1.9,FPS,Valorant,Multi-platform,8.7,Good,Rarely,...,False,False,False,0.1,9.7,1,14.5,16.75,7,Low
321,GD0322,20,Female,5.2,FPS,Valorant,Multi-platform,5.3,Good,Often,...,False,False,False,1.2,7.2,4,6.5,38.79,2,Low
345,GD0346,25,Male,5.1,FPS,Valorant,Multi-platform,6.0,Very Poor,Sometimes,...,False,True,False,0.7,9.0,3,11.5,76.51,10,Low
415,GD0416,17,Male,7.5,FPS,Valorant,PC,5.0,Poor,Rarely,...,False,True,False,1.1,6.9,2,6.7,135.83,2,Moderate
478,GD0479,23,Male,4.0,FPS,Valorant,Mobile,5.6,Poor,Never,...,False,False,False,1.6,7.1,2,12.3,41.19,7,Low
506,GD0507,21,Male,5.5,FPS,Valorant,Multi-platform,6.3,Fair,Sometimes,...,False,True,False,1.6,9.1,3,6.0,91.49,11,Low
523,GD0524,17,Male,4.6,FPS,Valorant,Multi-platform,6.2,Good,Sometimes,...,False,False,False,2.5,9.1,6,8.6,40.53,4,Low
525,GD0526,16,Male,1.7,FPS,Valorant,Multi-platform,8.2,Poor,Sometimes,...,False,False,False,0.8,7.6,1,9.7,12.32,4,Low
562,GD0563,16,Male,7.6,FPS,Valorant,Mobile,3.3,Insomnia,Always,...,False,False,True,4.6,6.9,3,4.1,42.16,1,Moderate
642,GD0643,22,Male,2.5,FPS,Valorant,Mobile,8.1,Fair,Always,...,False,False,False,0.0,8.7,3,10.5,28.41,3,Low
663,GD0664,16,Male,4.5,FPS,Valorant,Console,5.1,Poor,Never,...,False,False,False,0.4,7.0,4,6.2,104.97,6,Low
680,GD0681,19,Male,8.2,FPS,Valorant,Mobile,4.0,Poor,Sometimes,...,True,False,True,1.1,5.2,4,4.5,41.81,1,Moderate
687,GD0688,19,Female,12.3,FPS,Valorant,PC,3.5,Fair,Sometimes,...,False,False,True,1.6,4.4,9,1.6,413.29,9,Severe
690,GD0691,26,Male,4.8,FPS,Valorant,Multi-platform,6.3,Good,Rarely,...,False,True,False,2.3,9.2,4,6.6,107.55,3,Low
713,GD0714,20,Male,11.1,FPS,Valorant,Mobile,5.6,Fair,Rarely,...,True,False,True,0.4,5.8,6,2.0,396.00,4,Severe
728,GD0729,21,Male,8.4,FPS,Valorant,Multi-platform,5.1,Poor,Never,...,True,False,True,1.8,5.8,6,2.8,73.12,8,Severe
756,GD0757,27,Male,1.5,FPS,Valorant,Mobile,9.0,Good,Sometimes,...,False,False,False,0.5,10.4,1,12.0,10.08,12,Low
762,GD0763,22,Male,5.5,FPS,Valorant,Console,6.0,Insomnia,Often,...,False,True,False,0.8,8.8,3,9.6,91.34,10,Low
772,GD0773,19,Male,2.2,FPS,Valorant,Console,8.9,Good,Always,...,False,False,False,0.1,9.0,1,14.0,38.09,3,Low
780,GD0781,21,Female,6.3,FPS,Valorant,PC,6.1,Good,Never,...,False,True,True,4.1,5.1,2,9.6,120.62,11,Moderate
781,GD0782,18,Male,2.1,FPS,Valorant,PC,7.4,Good,Never,...,False,False,False,0.3,10.6,2,11.1,39.90,3,Low
936,GD0937,27,Male,4.9,FPS,Valorant,Console,6.1,Good,Sometimes,...,False,False,False,2.2,6.7,2,6.4,36.17,14,Low
945,GD0946,23,Male,2.5,FPS,Valorant,Console,8.2,Good,Sometimes,...,False,False,False,0.7,10.2,1,11.1,16.97,4,Low
965,GD0966,18,Other,7.6,FPS,Valorant,PC,4.8,Very Poor,Never,...,False,True,True,3.6,6.1,3,8.1,37.08,4,High
990,GD0991,19,Female,7.0,FPS,Valorant,PC,3.2,Fair,Often,...,False,False,True,1.4,7.7,5,5.8,121.06,2,Moderate

In [5]:
data.shape

(1000, 27)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 27 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   record_id                         1000 non-null   object
 1   age                               1000 non-null   int64
 2   gender                            1000 non-null   object
 3   daily_gaming_hours                1000 non-null   float64
 4   game_genre                        1000 non-null   object
 5   primary_game                      1000 non-null   object
 6   gaming_platform                   1000 non-null   object
 7   sleep_hours                       1000 non-null   float64
 8   sleep_quality                     1000 non-null   object
 9   sleep_disruption_frequency        1000 non-null   object
 10  academic_work_performance         1000 non-null   object
 11  grades_gpa                        754 non-null    float64
 12  work_productivity_score           674 non-null    float64
 13  mood_state                        1000 non-null   object
 14  mood_swing_frequency              1000 non-null   object
 15  withdrawal_symptoms               1000 non-null   bool
 16  loss_of_other_interests           1000 non-null   bool
 17  continued_despite_problems        1000 non-null   bool
 18  eye_strain                        1000 non-null   bool
 19  back_neck_pain                    1000 non-null   bool
 20  weight_change_kg                  1000 non-null   float64
 21  exercise_hours_weekly             1000 non-null   float64
 22  social_isolation_score            1000 non-null   int64
 23  face_to_face_social_hours_weekly  1000 non-null   float64
 24  monthly_game_spending_usd         1000 non-null   float64
 25  years_gaming                      1000 non-null   int64
 26  gaming_addiction_risk_level       1000 non-null   object
dtypes: bool(5), float64(8), int64(3), object(11)
memory usage: 176.9+ KB

In [7]:
data.describe()

,age,daily_gaming_hours,sleep_hours,grades_gpa,work_productivity_score,weight_change_kg,exercise_hours_weekly,social_isolation_score,face_to_face_social_hours_weekly,monthly_game_spending_usd,years_gaming
count,1000.000000,1000.000000,1000.000000,754.000000,674.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,20.475000,6.151400,5.738100,2.518037,5.394659,1.513400,6.945900,3.872000,7.654500,105.219730,5.796000
std,4.116105,2.867194,1.441213,0.872312,2.898742,1.432212,1.805027,2.091409,3.751954,113.886768,3.775532
min,13.000000,0.500000,3.000000,1.010000,1.000000,0.000000,0.700000,1.000000,0.000000,0.100000,1.000000
25%,18.000000,4.100000,4.800000,1.760000,3.000000,0.400000,5.700000,2.000000,5.000000,32.592500,3.000000
50%,20.000000,6.000000,5.700000,2.530000,5.000000,1.100000,7.000000,4.000000,8.000000,66.405000,5.000000
75%,22.000000,8.025000,6.600000,3.280000,8.000000,2.100000,8.200000,5.000000,10.400000,126.242500,8.000000
max,35.000000,15.100000,9.000000,4.000000,10.000000,8.900000,11.500000,10.000000,16.700000,499.270000,20.000000

In [8]:
data.isnull().sum()

record_id                             0
age                                   0
gender                                0
daily_gaming_hours                    0
game_genre                            0
primary_game                          0
gaming_platform                       0
sleep_hours                           0
sleep_quality                         0
sleep_disruption_frequency            0
academic_work_performance             0
grades_gpa                          246
work_productivity_score             326
mood_state                            0
mood_swing_frequency                  0
withdrawal_symptoms                   0
loss_of_other_interests               0
continued_despite_problems            0
eye_strain                            0
back_neck_pain                        0
weight_change_kg                      0
exercise_hours_weekly                 0
social_isolation_score                0
face_to_face_social_hours_weekly      0
monthly_game_spending_usd             0
years_gaming                          0
gaming_addiction_risk_level           0
dtype: int64

In [9]:
data_cleaned= data.drop(columns=['record_id', 'primary_game'])
data_cleaned['work_productivity_score'] = data_cleaned['work_productivity_score'].fillna(data_cleaned['work_productivity_score'].median())
data_cleaned['grades_gpa']=data_cleaned['grades_gpa'].fillna(data_cleaned['grades_gpa'].median())

In [10]:
data_cleaned.isnull().sum()

age                                 0
gender                              0
daily_gaming_hours                  0
game_genre                          0
gaming_platform                     0
sleep_hours                         0
sleep_quality                       0
sleep_disruption_frequency          0
academic_work_performance           0
grades_gpa                          0
work_productivity_score             0
mood_state                          0
mood_swing_frequency                0
withdrawal_symptoms                 0
loss_of_other_interests             0
continued_despite_problems          0
eye_strain                          0
back_neck_pain                      0
weight_change_kg                    0
exercise_hours_weekly               0
social_isolation_score              0
face_to_face_social_hours_weekly    0
monthly_game_spending_usd           0
years_gaming                        0
gaming_addiction_risk_level         0
dtype: int64

In [11]:
data_cleaned['gaming_addiction_risk_level'].value_counts()

gaming_addiction_risk_level
Low         514
Moderate    190
High        154
Severe      142
Name: count, dtype: int64

# Split Data

In [12]:
X = data_cleaned.drop("gaming_addiction_risk_level", axis=1)
y = data_cleaned["gaming_addiction_risk_level"]

In [13]:
X = pd.get_dummies(X)
le = LabelEncoder()
y = le.fit_transform(y)
X_train,X_temp,y_train,y_temp=train_test_split(X,y,test_size=0.3,random_state=42)
X_vald,X_test,y_vald,y_test=train_test_split(X_temp,y_temp,test_size=0.5,random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

# Build ANN

In [14]:
mlp = MLPClassifier(hidden_layer_sizes=(200,), max_iter=1000,random_state=1,activation='identity',solver='adam')
mlp.fit(X_train, y_train)

MLPClassifier(activation='identity', hidden_layer_sizes=(200,), max_iter=1000,
              random_state=1)

# Test Accuracy

In [15]:
X_test_scaled=scaler.transform(X_test)
y_pred_test = mlp.predict(X_test_scaled)
test_accuracy = accuracy_score(y_test, y_pred_test)
print("Test Accuracy:", (test_accuracy))

Test Accuracy: 0.9466666666666667

# Valdiation Accuracy

In [16]:
X_vald_scaled=scaler.transform(X_vald)
y_pred_vald = mlp.predict(X_vald_scaled)
val_accuracy = accuracy_score(y_vald, y_pred_vald)
print("Valdiation Accuracy:", (val_accuracy))

Valdiation Accuracy: 0.9266666666666666